"""
https://projecteuler.net/problem=2

Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""


def fibonacci_sequence(max_value=100):
    sequence = [1]
    fibo_value = 2

    while fibo_value <= max_value:
        sequence.append(fibo_value)
        fibo_value += sequence[-2]

    return sequence


def sum_even_values(sequence):
    return sum(value for value in sequence if value % 2 == 0)


if __name__ == '__main__':
    assert sum_even_values(fibonacci_sequence()) == 44
    assert sum_even_values(fibonacci_sequence(4_000_000)) == 4613732
